#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/home/java/gwt-2.0.0/gwt-user.jar:/home/java/gwt-2.0.1/gwt-dev.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.cs.amoba.Amoba/Amoba.html;
